// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stock.Api.Services;

#nullable disable

namespace Stock.Api.Migrations
{
    [DbContext(typeof(StockDbContext))]
    partial class StockDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stock.Api.Models.Entities.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e4393158-0595-47a9-b36f-36b9b7b9fe96"),
                            Count = 200,
                            ProductId = new Guid("6f3d5a32-b5b2-4eff-a3a7-a69ca46f9691")
                        },
                        new
                        {
                            Id = new Guid("c05e5da8-0bbc-427d-8ee7-31a99fdfb9fa"),
                            Count = 123,
                            ProductId = new Guid("71d41dd6-4b2d-4d7f-be75-9609cb31b5dd")
                        },
                        new
                        {
                            Id = new Guid("64743bae-fc71-4902-af24-500c901b1a6f"),
                            Count = 13,
                            ProductId = new Guid("4c6ca521-6c92-4cc7-b631-7f639675c2e6")
                        },
                        new
                        {
                            Id = new Guid("833fe012-fcb7-4e9e-a9ba-1c52655fde7d"),
                            Count = 5,
                            ProductId = new Guid("2a6251af-63b6-49d3-b2a4-e078f5299a77")
                        },
                        new
                        {
                            Id = new Guid("9df1ff08-1f24-44d5-a45f-bfb7578f004d"),
                            Count = 77,
                            ProductId = new Guid("74356621-9660-4cf9-9eba-c90e19448ef5")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
